const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const childProcess = require('node:child_process');

// Safety net: an unstubbed `pod install` cannot reach real cocoapods from an empty PATH.
process.env.PATH = path.join(os.tmpdir(), 'pw-no-cocoapods-on-path');

const PLUGIN_ID = 'pushwoosh-cordova-plugin';

const PODFILE = [
    '# DO NOT MODIFY -- auto-generated by Apache Cordova',
    "platform :ios, '13.0'",
    'use_frameworks!',
    "target 'HelloCordova' do",
    "\tproject 'HelloCordova.xcodeproj'",
    "\tpod 'PushwooshXCFramework', '7.2.4'",
    "\tpod 'PushwooshInboxUIXCFramework', '7.0.3'",
    'end',
    ''
].join('\n');

const VOIP_LINE = "\tpod 'PushwooshXCFramework/PushwooshVoIP', '7.2.4'";

function podfileWith(voipLine) {
    return PODFILE.replace(
        "\tpod 'PushwooshXCFramework', '7.2.4'\n",
        `\tpod 'PushwooshXCFramework', '7.2.4'\n${voipLine}\n`
    );
}

function project(t, { variables, podfile } = {}) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'pw-cordova-'));
    t.after(() => fs.rmSync(root, { recursive: true, force: true }));

    if (variables) {
        fs.mkdirSync(path.join(root, 'plugins'), { recursive: true });
        fs.writeFileSync(
            path.join(root, 'plugins', 'fetch.json'),
            JSON.stringify({
                [PLUGIN_ID]: { source: { type: 'registry', id: PLUGIN_ID }, is_top_level: true, variables }
            })
        );
    }

    if (podfile !== undefined) {
        fs.mkdirSync(path.join(root, 'platforms', 'ios'), { recursive: true });
        fs.writeFileSync(podfilePath(root), podfile);
    }

    return root;
}

function podfilePath(root) {
    return path.join(root, 'platforms', 'ios', 'Podfile');
}

function readPodfile(root) {
    return fs.readFileSync(podfilePath(root), 'utf8');
}

function stubExecSync(t) {
    return t.mock.method(childProcess, 'execSync', () => '');
}

function silenceConsole(t) {
    t.mock.method(console, 'log', () => {});
}

function context(root) {
    return { opts: { projectRoot: root, platforms: ['ios'], plugin: { id: PLUGIN_ID } } };
}

function loadHook(name) {
    const resolved = require.resolve(`../${name}`);
    delete require.cache[resolved];
    return require(resolved);
}

module.exports = {
    PLUGIN_ID,
    PODFILE,
    VOIP_LINE,
    podfileWith,
    project,
    podfilePath,
    readPodfile,
    stubExecSync,
    silenceConsole,
    context,
    loadHook
};
