'use strict';

const fs = require('node:fs');
const path = require('node:path');

// xcode and cordova-ios come from `npm install` in newdemo: on a fresh clone the suites that need them skip, not fail.
const DEMO_MODULES = ['xcode', 'cordova-ios/package.json', 'cordova-common'];
const missingModules = DEMO_MODULES.filter((name) => {
    try {
        require.resolve(name);
        return false;
    } catch {
        return true;
    }
});
const demoModulesMissing = missingModules.length > 0 && `${missingModules.join(', ')} not installed: run npm install in newdemo`;

// The pbxproj cordova-ios generates is its template with two placeholders filled in (lib/create.js).
function templatePbxproj({ name = 'newdemo', id = 'org.example.sampleapp' } = {}) {
    const template = path.join(
        path.dirname(require.resolve('cordova-ios/package.json')),
        'templates', 'project', '__PROJECT_NAME__.xcodeproj', 'project.pbxproj'
    );
    return fs.readFileSync(template, 'utf8')
        .replace(/__PROJECT_NAME__/g, name)
        .replace(/__PROJECT_ID__/g, id);
}

// Exactly what cordova-ios 7.1.1 writes for newdemo with the Pushwoosh plugin installed.
const PODFILE = [
    '# DO NOT MODIFY -- auto-generated by Apache Cordova',
    "source 'https://cdn.cocoapods.org/'",
    "platform :ios, '15.0'",
    'use_frameworks!',
    "target 'newdemo' do",
    "\tproject 'newdemo.xcodeproj'",
    "\tpod 'PushwooshXCFramework', '7.2.8'",
    "\tpod 'PushwooshInboxUIXCFramework', '7.0.42'",
    'end',
    ''
].join('\n');

module.exports = { templatePbxproj, PODFILE, demoModulesMissing };
